name: hds_forecast_2022
channels:
  - conda-forge
dependencies:
  - ipywidgets=7.6.5
  - jupyterlab=3.2.4
  - jupyterlab-plotly-extension=1.0.0
  - matplotlib=3.5.0
  - numpy=1.21.4
  - pandas=1.3.4
  - pip=21.0.1
  - plotly=5.4.0
  - python=3.8.8
  - pytorch==1.10.0
  - scipy=1.7.3
  - seaborn=0.11.2
  - statsmodels=0.11.1
  - pip:
    - tensorflow==2.7.0
    - pmdarima==1.6.0
    - scikit-learn==0.23.0
    - pystan==2.19.1.1
    - prophet==1.0.1
    - forecast-tools==0.1.6
