name: hds_forecast
channels:
  - conda-forge
dependencies:
  - ipywidgets=8.1.1
  - jupyterlab=4.0.9
  - jupyterlab-plotly-extension=1.0.0
  - jupyterlab-spellchecker=0.8.4
  - matplotlib=3.8.2
  - numpy=1.26.2
  - pandas=2.1.4
  - pip=23.3.1
  - plotly=5.18.0
  - python=3.10.13
  - scipy=1.11.4
  - seaborn=0.13.0
  - statsmodels=0.14.0
  - pip:
    - tensorflow-cpu==2.14.0
    - pmdarima==2.0.4
    - scikit-learn==1.3.2
    - prophet==1.1.5
    - forecast-tools==0.2.1

